### ISSUE TITLE
Make home page includes configurable

### ISSUE THREAD

**Issue by berendt** [opentelekomcloud-infra/gitstyring#26]
The lists displayed on the home page for Releases, Environments, and Packages should be configurable.

**Comment by gtema** [comment]
Not sure there is API for that. Browsing through official docs I haven't found anything in this direction

**Comment by berendt** [comment]
Too bad. I thought I might have just overlooked it in my search :(

**Comment by tibeer** [comment]
Can confirm, API only provides only the parameters listed here: https://docs.github.com/en/rest/repos/repos#create-an-organization-repository Unfortunately no option to set URLs for Releases, Environments and Packages :/ @gtema I guess this can be closed then.
