### ISSUE TITLE
Move OTC repositories into a separate repository

### ISSUE THREAD

**Issue by berendt** [opentelekomcloud-infra/gitstyring#36]
Currently, the teams and repositories of the OTC are managed with here in this repository.

We use gitstyring to manage our organisations and have included gitstyring as a submodule. With a job that updates the submodule daily via PR if there has been a change. We are not really interested in the changes to the OTC-specific configurations.

Therefore, I would like to suggest removing the OTC specific configuration from this repository and moving it to a separate repository for it.

As an example of how we did it: https://github.com/osism/github-permissions

**Comment by gtema** [comment]
You actually started using this not in the way how we are using it now: for us this is really the config itself. Playbooks and roles are part of the system-config, but were not dropped here.
Instead (and this is what we were thinking about since some time) we will create ansible collection with the role and playbook (in the long run modules will be created for that)

**Comment by berendt** [comment]
Ok. Of course, moving the roles and playbooks into a collection also works and would be the preferred solution.

**Comment by gtema** [comment]
Moving stuff into https://github.com/opentelekomcloud/ansible-collection-gitcontrol now.
We are going to switch out system-config jobs to be using this collection to test how this works. When completed will drop roles/playbooks from here. Please report moving issues in the new repo.
Once stuff stabilizes there we will release the collection, if you can test on dev state - early feedback welcome. The only issue is invocation of the playbook from the collection: you either pass whole pass to the playbook from the installed collection or you copy the playbook into your CD

**Comment by berendt** [comment]
Thank you for the quick implementation. From my point of view, the issue can be closed.

**Comment by gtema** [comment]
Collection is implemented, but not yet released. Please switch to it and provide feedback. You only change the playbook (as in `https://github.com/opentelekomcloud/ansible-collection-gitcontrol/blob/main/playbooks/run.yaml`. Set `gitstyring_root_dir` (should point to root now, and not to ./orgs and branch protection templates go also to this root) and `github_token` (and optionally `github_url`)
